service: emails-providers
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_REDIRECT_URL: ${env:GOOGLE_REDIRECT_URL}
    MAIL_TABLE_NAME: mail-table-${self:provider.stage}
    MAIL_QUEUE_NAME: mail-queue-${self:provider.stage}
    MAIL_BUCKET_NAME: mail-bucket-${self:provider.stage}

custom:
  api-url: 'hola'

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  - serverless-offline

functions:
  - ${file(infrastructure/functions/mail/google-mail.yml)}
  - ${file(infrastructure/functions/mail/graph-mail.yml)}

resources:
  - ${file(infrastructure/resources/buckets.yml)}
  - ${file(infrastructure/resources/queues.yml)}
  - ${file(infrastructure/resources/tables.yml)}

package:
  individually: true
  patterns:
    - '!**/*'
